# Generated by Django 6.0.4 on 2026-05-07 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veteriner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=300)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('uzmanlik', models.CharField(default='Genel Veterinerlik', max_length=100)),
                ('puan', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Veteriner',
            },
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hayvan_adi', models.CharField(max_length=100)),
                ('sahip_adi', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('tarih', models.DateField()),
                ('neden', models.TextField()),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('onaylandi', 'Onaylandı'), ('iptal', 'İptal')], default='bekliyor', max_length=20)),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to=settings.AUTH_USER_MODEL)),
                ('veteriner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='veteriner.veteriner')),
            ],
            options={
                'ordering': ['-olusturuldu'],
            },
        ),
    ]
