# Generated by Django 6.0.4 on 2026-05-07 08:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.CharField(max_length=500)),
                ('olusturuldu', models.DateTimeField(default=django.utils.timezone.now)),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anketler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-olusturuldu'],
            },
        ),
        migrations.CreateModel(
            name='AnketSecenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.CharField(max_length=300)),
                ('oy_sayisi', models.PositiveIntegerField(default=0)),
                ('sira', models.PositiveSmallIntegerField(default=0)),
                ('anket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secenekler', to='sosyal.anket')),
            ],
            options={
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Gonderi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(blank=True)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='gonderiler/')),
                ('olusturuldu', models.DateTimeField(default=django.utils.timezone.now)),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderiler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-olusturuldu'],
            },
        ),
        migrations.AddField(
            model_name='anket',
            name='gonderi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anket', to='sosyal.gonderi'),
        ),
        migrations.CreateModel(
            name='Sohbet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('kanal', models.BooleanField(default=False)),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('uyeler', models.ManyToManyField(blank=True, related_name='sohbetler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField()),
                ('gonderildi', models.DateTimeField(auto_now_add=True)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sohbet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='sosyal.sohbet')),
            ],
            options={
                'ordering': ['gonderildi'],
            },
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField()),
                ('olusturuldu', models.DateTimeField(auto_now_add=True)),
                ('gonderi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='sosyal.gonderi')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['olusturuldu'],
            },
        ),
        migrations.CreateModel(
            name='AnketOy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('anket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oylar', to='sosyal.anket')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('secenek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sosyal.anketsecenek')),
            ],
            options={
                'unique_together': {('anket', 'kullanici')},
            },
        ),
        migrations.CreateModel(
            name='GonderiBegeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gonderi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='begeniler', to='sosyal.gonderi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('gonderi', 'kullanici')},
            },
        ),
    ]
