# Generated by Django 6.0.4 on 2026-05-07 08:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kampanya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('hedef', models.DecimalField(decimal_places=2, max_digits=10)),
                ('toplanan', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('emoji', models.CharField(default='❤️', max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('olusturuldu', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-olusturuldu'],
            },
        ),
        migrations.CreateModel(
            name='Bagis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ad_soyad', models.CharField(blank=True, default='Anonim', max_length=100)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bagislar', to=settings.AUTH_USER_MODEL)),
                ('kampanya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bagislar', to='bagis.kampanya')),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
    ]
