# Generated by Django 6.0.4 on 2026-05-07 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatarlar/')),
                ('sosyal_bildirim', models.BooleanField(default=True)),
                ('etkinlik_bildirim', models.BooleanField(default=False)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rozet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('ilk_dost', 'İlk Dost'), ('comert_pati', 'Cömert Pati'), ('kayip_avci', 'Kayıp Avcısı'), ('kahraman', 'Kahraman')], max_length=30)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rozetler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kullanici', 'tur')},
            },
        ),
    ]
